package GUIMain;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Clear.java
 *
 * Created on Feb 22, 2010, 9:59:13 PM
 */

/**
 *
 * @author Kal
 */
public class Clear extends javax.swing.JPanel {

    /** Creates new form Clear */
    public Clear() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BClear = new javax.swing.JButton();
        BClearEntered = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();

        BClear.setText("C");
        BClear.setMaximumSize(new java.awt.Dimension(60, 23));
        BClear.setMinimumSize(new java.awt.Dimension(60, 23));
        BClear.setPreferredSize(new java.awt.Dimension(60, 23));
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearActionPerformed(evt);
            }
        });

        BClearEntered.setText("CE");
        BClearEntered.setMaximumSize(new java.awt.Dimension(60, 23));
        BClearEntered.setMinimumSize(new java.awt.Dimension(60, 23));
        BClearEntered.setPreferredSize(new java.awt.Dimension(60, 23));
        BClearEntered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearEnteredActionPerformed(evt);
            }
        });

        BDelete.setText("DEL");
        BDelete.setMaximumSize(new java.awt.Dimension(60, 23));
        BDelete.setMinimumSize(new java.awt.Dimension(60, 23));
        BDelete.setPreferredSize(new java.awt.Dimension(60, 23));
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BClearEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BClearEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClearActionPerformed
        GUI.eq="";
        GUI.hist="";
        GUI.ans="";
        GUI.TextDisp.setText("");
        GUI.graphOut1.gr.clearFunction();
        GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphOut1.repaint();
		GUI.tableOut1.gr.clearTable();
        GUI.tableOut1.i=GUI.tableOut1.gr.drawTable();
		GUI.tableOut1.repaint();
    }//GEN-LAST:event_BClearActionPerformed

    private void BClearEnteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClearEnteredActionPerformed
        GUI.eq="";
       GUI.TextDisp.setText(GUI.hist);
    }//GEN-LAST:event_BClearEnteredActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        if (GUI.eq.length()<2)
        {
        	GUI.eq="";
        	GUI.TextDisp.setText(GUI.hist+GUI.eq);
        	return;
        }
    	if (GUI.eq.charAt(GUI.eq.length()-1)>47 && GUI.eq.charAt(GUI.eq.length()-1)<58)
    	{
    		GUI.eq=GUI.eq.substring(0, GUI.eq.length()-1);
    	       GUI.TextDisp.setText(GUI.hist+GUI.eq);
    	       return;
    	}
    	GUI.eq=GUI.eq.substring(0, GUI.eq.length()-1);
    	while (GUI.eq.charAt(GUI.eq.length()-1)!=' ')
    	{
    		GUI.eq=GUI.eq.substring(0, GUI.eq.length()-1);
    	}
    	GUI.eq=GUI.eq.substring(0, GUI.eq.length()-1);
    	GUI.TextDisp.setText(GUI.hist+GUI.eq);
	       return;
        
        
    }//GEN-LAST:event_BDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClear;
    private javax.swing.JButton BClearEntered;
    private javax.swing.JButton BDelete;
    // End of variables declaration//GEN-END:variables

}
