/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphOut.java
 *
 * Created on Feb 23, 2010, 12:50:22 AM
 */

package GUIMain;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

import Graph.Graph;

/**
 *
 * @author Kal
 */
public class GraphOut extends javax.swing.JPanel {

    /** Creates new form GraphOut */
    public GraphOut() {
    	
        initComponents();
    }
    @Override
 public void paintComponent(Graphics g) {
       g.drawImage(i,0, 0, this);
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
BufferedImage i;
Graph gr = new Graph();
}
