/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Powers.java
 *
 * Created on Mar 10, 2010, 8:46:26 PM
 */

package GUIMain;

/**
 *
 * @author Kal
 */
public class Powers extends javax.swing.JPanel {

    /** Creates new form Powers */
    public Powers() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BCarat = new javax.swing.JButton();
        Bsqrt = new javax.swing.JButton();
        Be = new javax.swing.JButton();
        Blog = new javax.swing.JButton();
        Bln = new javax.swing.JButton();

        BCarat.setText("^(");
        BCarat.setPreferredSize(new java.awt.Dimension(55, 23));
        BCarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCaratActionPerformed(evt);
            }
        });

        Bsqrt.setText("SQRT");
        Bsqrt.setPreferredSize(new java.awt.Dimension(55, 23));
        Bsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsqrtActionPerformed(evt);
            }
        });

        Be.setText("e^(");
        Be.setPreferredSize(new java.awt.Dimension(55, 23));
        Be.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeActionPerformed(evt);
            }
        });

        Blog.setText("log(");
        Blog.setPreferredSize(new java.awt.Dimension(55, 23));
        Blog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlogActionPerformed(evt);
            }
        });

        Bln.setText("ln(");
        Bln.setPreferredSize(new java.awt.Dimension(55, 23));
        Bln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BCarat, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bsqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Be, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Blog, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bln, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BCarat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Bsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Be, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Blog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Bln, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BCaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCaratActionPerformed
        GUI.eq+=" ^( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
}//GEN-LAST:event_BCaratActionPerformed

    private void BsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsqrtActionPerformed
        GUI.eq+=" sqrt( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BsqrtActionPerformed

    private void BeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeActionPerformed
        GUI.eq+=" e^( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BeActionPerformed

    private void BlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlogActionPerformed
        GUI.eq+=" log( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BlogActionPerformed

    private void BlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlnActionPerformed
        GUI.eq+=" ln( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BlnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCarat;
    private javax.swing.JButton Be;
    private javax.swing.JButton Bln;
    private javax.swing.JButton Blog;
    private javax.swing.JButton Bsqrt;
    // End of variables declaration//GEN-END:variables

}
