/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicOPS.java
 *
 * Created on Feb 22, 2010, 5:15:23 PM
 */

package GUIMain;

import Handler.HandlerMain;

/**
 *
 * @author Kal
 */
public class BasicOPS extends javax.swing.JPanel {

    /** Creates new form BasicOPS */
    public BasicOPS() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bdev = new javax.swing.JButton();
        Btimes = new javax.swing.JButton();
        Bsub = new javax.swing.JButton();
        Badd = new javax.swing.JButton();
        Beq = new javax.swing.JButton();

        Bdev.setText("/");
        Bdev.setMaximumSize(new java.awt.Dimension(60, 23));
        Bdev.setMinimumSize(new java.awt.Dimension(60, 23));
        Bdev.setPreferredSize(new java.awt.Dimension(60, 23));
        Bdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdevActionPerformed(evt);
            }
        });

        Btimes.setText("*");
        Btimes.setMaximumSize(new java.awt.Dimension(60, 23));
        Btimes.setMinimumSize(new java.awt.Dimension(60, 23));
        Btimes.setPreferredSize(new java.awt.Dimension(60, 23));
        Btimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtimesActionPerformed(evt);
            }
        });

        Bsub.setText("-");
        Bsub.setMaximumSize(new java.awt.Dimension(60, 23));
        Bsub.setMinimumSize(new java.awt.Dimension(60, 23));
        Bsub.setPreferredSize(new java.awt.Dimension(60, 23));
        Bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsubActionPerformed(evt);
            }
        });

        Badd.setText("+");
        Badd.setMaximumSize(new java.awt.Dimension(60, 23));
        Badd.setMinimumSize(new java.awt.Dimension(60, 23));
        Badd.setPreferredSize(new java.awt.Dimension(60, 23));
        Badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaddActionPerformed(evt);
            }
        });

        Beq.setText("=");
        Beq.setMaximumSize(new java.awt.Dimension(60, 23));
        Beq.setMinimumSize(new java.awt.Dimension(60, 23));
        Beq.setPreferredSize(new java.awt.Dimension(60, 23));
        Beq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bdev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Btimes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Badd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Beq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Badd, Bdev, Beq, Bsub, Btimes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bdev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btimes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Badd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Beq, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Badd, Bdev, Beq, Bsub, Btimes});

    }// </editor-fold>//GEN-END:initComponents

    private void BdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdevActionPerformed
    	if (GUI.eq.equals("")&&!GUI.ans.startsWith("Inv"))
            GUI.eq=GUI.ans;
        GUI.eq+=" / ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BdevActionPerformed

    private void BtimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtimesActionPerformed
    	if (GUI.eq.equals("")&&!GUI.ans.startsWith("Inv"))
            GUI.eq=GUI.ans;
        GUI.eq+=" * ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BtimesActionPerformed

    private void BsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsubActionPerformed
    	if (GUI.eq.equals("")&&!GUI.ans.startsWith("Inv"))
            GUI.eq=GUI.ans;
        GUI.eq+=" - ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BsubActionPerformed

    private void BaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaddActionPerformed
    	if (GUI.eq.equals("")&&!GUI.ans.startsWith("Inv"))
            GUI.eq=GUI.ans;
        GUI.eq+=" + ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BaddActionPerformed

    private void BeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeqActionPerformed
    	GUI.hist+=GUI.eq+" = "+HandlerMain.handle(GUI.eq)+"\n";
        GUI.ans=HandlerMain.handle(GUI.eq) + " ";
        GUI.eq="";
        GUI.TextDisp.setText(GUI.hist);
    }//GEN-LAST:event_BeqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badd;
    private javax.swing.JButton Bdev;
    javax.swing.JButton Beq;
    private javax.swing.JButton Bsub;
    private javax.swing.JButton Btimes;
    // End of variables declaration//GEN-END:variables

}
