/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Graphing.java
 *
 * Created on Feb 23, 2010, 8:54:53 PM
 */

package GUIMain;

import Graph.Function;
import Graph.Graph;
import Graph.Table;
import Handler.HandlerMain;

/**
 *
 * @author Kal
 */
public class Graphing extends javax.swing.JPanel {

	/** Creates new form Graphing */
	public Graphing() {
		initComponents();
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Byeq = new javax.swing.JButton();
		BX = new javax.swing.JButton();
		Bgraph = new javax.swing.JButton();

		Byeq.setText("Y=");
		Byeq.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ByeqActionPerformed(evt);
			}
		});

		BX.setText("X");
		BX.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BXActionPerformed(evt);
			}
		});

		Bgraph.setText("GRAPH");
		Bgraph.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BgraphActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(Byeq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(Bgraph, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BX, Bgraph, Byeq});

		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
						.addComponent(Byeq, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(Bgraph, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BX, Bgraph, Byeq});

	}// </editor-fold>//GEN-END:initComponents

	private void ByeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByeqActionPerformed
		GUI.eq+=" Y= ";
		GUI.TextDisp.setText(GUI.hist+GUI.eq);
	}//GEN-LAST:event_ByeqActionPerformed

	private void BXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BXActionPerformed
		GUI.eq+=" X ";
		GUI.TextDisp.setText(GUI.hist+GUI.eq);
	}//GEN-LAST:event_BXActionPerformed

	private void BgraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgraphActionPerformed
		if (GUI.eq.startsWith(" Y="))
		{
			GUI.eq="Y = "+GUI.eq.substring(3);
		}
		else 
		{
			GUI.hist+=GUI.eq+"\n Invalid Graph\n";
	        GUI.eq="";
	        GUI.TextDisp.setText(GUI.hist);
	        return;
		}
		if (HandlerMain.handle(GUI.eq).equals("Invalid Graph")||
				HandlerMain.handle(GUI.eq).equals("Invalid Data")||
				HandlerMain.handle(GUI.eq).equals("Invalid Entry"))
		{
			GUI.hist+=GUI.eq+"\n Invalid Graph\n";
	        GUI.eq="";
	        GUI.TextDisp.setText(GUI.hist);
		}
		else
		{
			GUI.graphOut1.gr.setFunction(new Function(HandlerMain.handle(GUI.eq)));
			GUI.graphOut1.i=GUI.graphOut1.gr.draw();
			GUI.graphOut1.repaint();
			
			GUI.tableOut1.gr.setTable((new Function(HandlerMain.handle(GUI.eq))));
			GUI.tableOut1.i=GUI.tableOut1.gr.drawTable();
			GUI.tableOut1.repaint();
			GUI.hist+=GUI.eq+"\n";
	        GUI.eq="";
	        GUI.TextDisp.setText(GUI.hist);
		}
	}//GEN-LAST:event_BgraphActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BX;
	private javax.swing.JButton Bgraph;
	private javax.swing.JButton Byeq;
	// End of variables declaration//GEN-END:variables

}
