/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphParas.java
 *
 * Created on Mar 8, 2010, 7:30:17 PM
 */

package GUIMain;

/**
 *
 * @author Kal
 */
public class GraphParas extends javax.swing.JPanel {

	/** Creates new form GraphParas */
	public GraphParas() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        posVerifyer1 = new GUIMain.PosVerifyer();
        generalVerifyer1 = new GUIMain.GeneralVerifyer();
        LXmax = new javax.swing.JLabel();
        LXmin = new javax.swing.JLabel();
        LYmax = new javax.swing.JLabel();
        LYmin = new javax.swing.JLabel();
        LXscl = new javax.swing.JLabel();
        LYscl = new javax.swing.JLabel();
        BAxesOff = new javax.swing.JRadioButton();
        BAxesOn = new javax.swing.JRadioButton();
        Axes = new javax.swing.JLabel();
        LExpr = new javax.swing.JLabel();
        BExprOn = new javax.swing.JRadioButton();
        BExprOff = new javax.swing.JRadioButton();
        LTblStart = new javax.swing.JLabel();
        LTblDiff = new javax.swing.JLabel();
        FXmax = new javax.swing.JFormattedTextField();
        FXscl = new javax.swing.JFormattedTextField();
        FYmax = new javax.swing.JFormattedTextField();
        FYScl = new javax.swing.JFormattedTextField();
        FYmin = new javax.swing.JFormattedTextField();
        FTblDiff = new javax.swing.JFormattedTextField();
        FTblStart = new javax.swing.JFormattedTextField();
        FXmin = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(259, 197));

        LXmax.setText("Xmax");
        LXmax.setPreferredSize(new java.awt.Dimension(35, 20));

        LXmin.setText("Xmin");
        LXmin.setPreferredSize(new java.awt.Dimension(35, 20));

        LYmax.setText("Ymax");
        LYmax.setPreferredSize(new java.awt.Dimension(35, 20));

        LYmin.setText("Ymin");
        LYmin.setPreferredSize(new java.awt.Dimension(35, 20));

        LXscl.setText("Xscl");
        LXscl.setPreferredSize(new java.awt.Dimension(35, 20));

        LYscl.setText("Yscl");
        LYscl.setPreferredSize(new java.awt.Dimension(35, 20));

        buttonGroup1.add(BAxesOff);
        BAxesOff.setText("Off");
        BAxesOff.setPreferredSize(new java.awt.Dimension(45, 20));
        BAxesOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAxesOffActionPerformed(evt);
            }
        });

        buttonGroup1.add(BAxesOn);
        BAxesOn.setSelected(true);
        BAxesOn.setText("On");
        BAxesOn.setPreferredSize(new java.awt.Dimension(45, 20));
        BAxesOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAxesOnActionPerformed(evt);
            }
        });

        Axes.setText("Axes");
        Axes.setPreferredSize(new java.awt.Dimension(50, 20));

        LExpr.setText("Expr");
        LExpr.setPreferredSize(new java.awt.Dimension(50, 20));

        buttonGroup2.add(BExprOn);
        BExprOn.setSelected(true);
        BExprOn.setText("On");
        BExprOn.setPreferredSize(new java.awt.Dimension(45, 20));
        BExprOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExprOnActionPerformed(evt);
            }
        });

        buttonGroup2.add(BExprOff);
        BExprOff.setText("Off");
        BExprOff.setPreferredSize(new java.awt.Dimension(45, 20));
        BExprOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExprOffActionPerformed(evt);
            }
        });

        LTblStart.setText("TblStart");
        LTblStart.setPreferredSize(new java.awt.Dimension(50, 20));

        LTblDiff.setText("TblDiff");
        LTblDiff.setPreferredSize(new java.awt.Dimension(50, 20));

        FXmax.setText("10");
        FXmax.setInputVerifier(generalVerifyer1);
        FXmax.setPreferredSize(new java.awt.Dimension(50, 20));
        FXmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FXmaxActionPerformed(evt);
            }
        });
        FXmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FXmaxFocusLost(evt);
            }
        });

        FXscl.setText("1");
        FXscl.setInheritsPopupMenu(true);
        FXscl.setInputVerifier(posVerifyer1);
        FXscl.setPreferredSize(new java.awt.Dimension(50, 20));
        FXscl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FXsclActionPerformed(evt);
            }
        });
        FXscl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FXsclFocusLost(evt);
            }
        });

        FYmax.setText("10");
        FYmax.setInputVerifier(generalVerifyer1);
        FYmax.setPreferredSize(new java.awt.Dimension(50, 20));
        FYmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FYmaxActionPerformed(evt);
            }
        });
        FYmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FYmaxFocusLost(evt);
            }
        });

        FYScl.setText("1");
        FYScl.setInputVerifier(posVerifyer1);
        FYScl.setPreferredSize(new java.awt.Dimension(50, 20));
        FYScl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FYSclActionPerformed(evt);
            }
        });
        FYScl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FYSclFocusLost(evt);
            }
        });

        FYmin.setText("-10");
        FYmin.setInputVerifier(generalVerifyer1);
        FYmin.setPreferredSize(new java.awt.Dimension(50, 20));
        FYmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FYminActionPerformed(evt);
            }
        });
        FYmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FYminFocusLost(evt);
            }
        });

        FTblDiff.setText("1");
        FTblDiff.setInputVerifier(posVerifyer1);
        FTblDiff.setPreferredSize(new java.awt.Dimension(50, 20));
        FTblDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTblDiffActionPerformed(evt);
            }
        });
        FTblDiff.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FTblDiffFocusLost(evt);
            }
        });

        FTblStart.setText("0");
        FTblStart.setInputVerifier(generalVerifyer1);
        FTblStart.setPreferredSize(new java.awt.Dimension(50, 20));
        FTblStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTblStartActionPerformed(evt);
            }
        });
        FTblStart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FTblStartFocusLost(evt);
            }
        });

        FXmin.setText("-10");
        FXmin.setInputVerifier(generalVerifyer1);
        FXmin.setPreferredSize(new java.awt.Dimension(50, 20));
        FXmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FXminActionPerformed(evt);
            }
        });
        FXmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FXminFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LXmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FXmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(LXmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FXmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LXscl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FXscl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Axes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LTblDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LTblStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LYmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FYmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(LYmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LExpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BAxesOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FYmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LYscl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BExprOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BAxesOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FYScl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FTblDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FTblStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BExprOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LXmax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LXmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LXscl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FXmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FXmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FXscl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LYmax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LYmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LYscl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FYScl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FYmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FYmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Axes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAxesOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAxesOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BExprOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BExprOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTblStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTblDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTblDiff, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void FXmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FXmaxActionPerformed
		GUI.graphOut1.gr.setXmax(Double.parseDouble(FXmax.getText()));
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_FXmaxActionPerformed

	private void FXsclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FXsclActionPerformed
		GUI.graphOut1.gr.setXscl(Double.parseDouble(FXscl.getText()));
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_FXsclActionPerformed

	private void FYmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FYmaxActionPerformed
		GUI.graphOut1.gr.setYmax(Double.parseDouble(FYmax.getText()));
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_FYmaxActionPerformed

	private void FYSclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FYSclActionPerformed
		GUI.graphOut1.gr.setYscl(Double.parseDouble(FYScl.getText()));
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_FYSclActionPerformed

	private void FYminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FYminActionPerformed
		GUI.graphOut1.gr.setYscl(Double.parseDouble(FYScl.getText()));
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_FYminActionPerformed

	private void FTblDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTblDiffActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_FTblDiffActionPerformed

	private void FTblStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTblStartActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_FTblStartActionPerformed

	private void BAxesOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAxesOnActionPerformed
		GUI.graphOut1.gr.setAxes(BAxesOn.isSelected());
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_BAxesOnActionPerformed

	private void FXminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FXminActionPerformed
		GUI.graphOut1.gr.setXmin(Double.parseDouble(FXmin.getText()));
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
	}//GEN-LAST:event_FXminActionPerformed

        private void BAxesOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAxesOffActionPerformed
            GUI.graphOut1.gr.setAxes(!BAxesOff.isSelected());
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
        }//GEN-LAST:event_BAxesOffActionPerformed

        private void BExprOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExprOffActionPerformed
            GUI.graphOut1.gr.setExpr(!BExprOff.isSelected());
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
        }//GEN-LAST:event_BExprOffActionPerformed

        private void BExprOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExprOnActionPerformed
            GUI.graphOut1.gr.setExpr(BExprOn.isSelected());
		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
		GUI.graphing1.repaint();
        }//GEN-LAST:event_BExprOnActionPerformed

        private void FXmaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FXmaxFocusLost
        	GUI.graphOut1.gr.setXmax(Double.parseDouble(FXmax.getText()));
    		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
    		GUI.graphing1.repaint();
        }//GEN-LAST:event_FXmaxFocusLost

        private void FXminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FXminFocusLost
        	GUI.graphOut1.gr.setXmin(Double.parseDouble(FXmin.getText()));
    		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
    		GUI.graphing1.repaint();
        }//GEN-LAST:event_FXminFocusLost

        private void FXsclFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FXsclFocusLost
        	GUI.graphOut1.gr.setXscl(Double.parseDouble(FXscl.getText()));
    		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
    		GUI.graphing1.repaint();
        }//GEN-LAST:event_FXsclFocusLost

        private void FYmaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FYmaxFocusLost
        	GUI.graphOut1.gr.setYmax(Double.parseDouble(FYmax.getText()));
    		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
    		GUI.graphing1.repaint();
        }//GEN-LAST:event_FYmaxFocusLost

        private void FYminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FYminFocusLost
        	GUI.graphOut1.gr.setYmin(Double.parseDouble(FYmin.getText()));
    		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
    		GUI.graphing1.repaint();
        }//GEN-LAST:event_FYminFocusLost

        private void FYSclFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FYSclFocusLost
        	GUI.graphOut1.gr.setYscl(Double.parseDouble(FYScl.getText()));
    		GUI.graphOut1.i=GUI.graphOut1.gr.draw();
    		GUI.graphing1.repaint();
        }//GEN-LAST:event_FYSclFocusLost

        private void FTblStartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FTblStartFocusLost
            GUI.tableOut1.gr.setTblStart(Double.parseDouble(FTblStart.getText()));
            GUI.tableOut1.i=GUI.tableOut1.gr.drawTable();
            GUI.tableOut1.repaint();
        }//GEN-LAST:event_FTblStartFocusLost

        private void FTblDiffFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FTblDiffFocusLost
        	GUI.tableOut1.gr.setTblDiff(Double.parseDouble(FTblDiff.getText()));
            GUI.tableOut1.i=GUI.tableOut1.gr.drawTable();
            GUI.tableOut1.repaint();
        }//GEN-LAST:event_FTblDiffFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Axes;
    private javax.swing.JRadioButton BAxesOff;
    private javax.swing.JRadioButton BAxesOn;
    private javax.swing.JRadioButton BExprOff;
    private javax.swing.JRadioButton BExprOn;
    private javax.swing.JFormattedTextField FTblDiff;
    private javax.swing.JFormattedTextField FTblStart;
    private javax.swing.JFormattedTextField FXmax;
    private javax.swing.JFormattedTextField FXmin;
    private javax.swing.JFormattedTextField FXscl;
    private javax.swing.JFormattedTextField FYScl;
    private javax.swing.JFormattedTextField FYmax;
    private javax.swing.JFormattedTextField FYmin;
    private javax.swing.JLabel LExpr;
    private javax.swing.JLabel LTblDiff;
    private javax.swing.JLabel LTblStart;
    private javax.swing.JLabel LXmax;
    private javax.swing.JLabel LXmin;
    private javax.swing.JLabel LXscl;
    private javax.swing.JLabel LYmax;
    private javax.swing.JLabel LYmin;
    private javax.swing.JLabel LYscl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private GUIMain.GeneralVerifyer generalVerifyer1;
    private GUIMain.PosVerifyer posVerifyer1;
    // End of variables declaration//GEN-END:variables

}
