package GUIMain;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Feb 11, 2010, 8:34:57 PM
 */

/**
 *
 * @author Khaled Al-Sherif
 */
public class GUI extends javax.swing.JFrame {

    static class GraphOut {

        public GraphOut() {
        }
    }

	/** Creates new GUI object*/
	public GUI() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextDisp = new javax.swing.JTextPane();
        Bopenpara = new javax.swing.JButton();
        Bclosepara = new javax.swing.JButton();
        trig1 = new GUIMain.Trig();
        nums1 = new GUIMain.Nums();
        clear1 = new GUIMain.Clear();
        basicOPS1 = new GUIMain.BasicOPS();
        graphing1 = new GUIMain.Graphing();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        graphOut1 = new GUIMain.GraphOut();
        tableOut1 = new GUIMain.TableOut();
        graphParas1 = new GUIMain.GraphParas();
        powers1 = new GUIMain.Powers();
        Babs = new javax.swing.JButton();
        Bopenpara2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        TextDisp.setEditable(false);
        jScrollPane1.setViewportView(TextDisp);

        Bopenpara.setText("(");
        Bopenpara.setPreferredSize(new java.awt.Dimension(55, 23));
        Bopenpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BopenparaActionPerformed(evt);
            }
        });

        Bclosepara.setText(")");
        Bclosepara.setPreferredSize(new java.awt.Dimension(55, 23));
        Bclosepara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcloseparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphOut1Layout = new javax.swing.GroupLayout(graphOut1);
        graphOut1.setLayout(graphOut1Layout);
        graphOut1Layout.setHorizontalGroup(
            graphOut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        graphOut1Layout.setVerticalGroup(
            graphOut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Graph", graphOut1);

        javax.swing.GroupLayout tableOut1Layout = new javax.swing.GroupLayout(tableOut1);
        tableOut1.setLayout(tableOut1Layout);
        tableOut1Layout.setHorizontalGroup(
            tableOut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        tableOut1Layout.setVerticalGroup(
            tableOut1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Table", tableOut1);

        graphParas1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                graphParas1FocusLost(evt);
            }
        });
        jTabbedPane1.addTab("Options", graphParas1);

        Babs.setText("abs(");
        Babs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BabsActionPerformed(evt);
            }
        });

        Bopenpara2.setText("CBRT");
        Bopenpara2.setPreferredSize(new java.awt.Dimension(55, 23));
        Bopenpara2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bopenpara2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(trig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nums1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(basicOPS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Bopenpara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bclosepara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(clear1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Babs, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bopenpara2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(powers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(trig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bopenpara, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Bclosepara, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nums1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(basicOPS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(powers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Babs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Bopenpara2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(graphing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bclosepara, Bopenpara});

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void BopenparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BopenparaActionPerformed
		eq+=" ( ";
		TextDisp.setText(hist+eq);
	}//GEN-LAST:event_BopenparaActionPerformed

	private void BcloseparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcloseparaActionPerformed
		eq+=" ) ";
		TextDisp.setText(hist+eq);
	}//GEN-LAST:event_BcloseparaActionPerformed

        private void graphParas1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_graphParas1FocusLost
        }//GEN-LAST:event_graphParas1FocusLost

        private void BabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BabsActionPerformed
                eq+=" abs( ";
		TextDisp.setText(hist+eq);
        }//GEN-LAST:event_BabsActionPerformed

        private void Bopenpara2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bopenpara2ActionPerformed
            eq+=" cbrt( ";
            TextDisp.setText(hist+eq);
        }//GEN-LAST:event_Bopenpara2ActionPerformed


	/**Launches the Calculator
	 * @param args Program does not take any arguments.
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Babs;
    private javax.swing.JButton Bclosepara;
    private javax.swing.JButton Bopenpara;
    private javax.swing.JButton Bopenpara2;
    static javax.swing.JTextPane TextDisp;
    static GUIMain.BasicOPS basicOPS1;
    static GUIMain.Clear clear1;
    static GUIMain.GraphOut graphOut1;
    static GUIMain.GraphParas graphParas1;
    static GUIMain.Graphing graphing1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    static GUIMain.Nums nums1;
    private GUIMain.Powers powers1;
    static GUIMain.TableOut tableOut1;
    static GUIMain.Trig trig1;
    // End of variables declaration//GEN-END:variables
	static String eq = "";
	static String ans = "";
	static String hist = "";
        public static int width = 331;
        public static int height = 248;
}
