/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Nums.java
 *
 * Created on Feb 22, 2010, 5:06:14 PM
 */

package GUIMain;

/**
 *
 * @author Kal
 */
public class Nums extends javax.swing.JPanel {

    /** Creates new form Nums */
    public Nums() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        Bpoint = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        Bneg = new javax.swing.JButton();

        B7.setText("7");
        B7.setMaximumSize(new java.awt.Dimension(60, 23));
        B7.setMinimumSize(new java.awt.Dimension(60, 23));
        B7.setPreferredSize(new java.awt.Dimension(60, 23));
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setText("8");
        B8.setMaximumSize(new java.awt.Dimension(60, 23));
        B8.setMinimumSize(new java.awt.Dimension(60, 23));
        B8.setPreferredSize(new java.awt.Dimension(60, 23));
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setText("9");
        B9.setMaximumSize(new java.awt.Dimension(60, 23));
        B9.setMinimumSize(new java.awt.Dimension(60, 23));
        B9.setPreferredSize(new java.awt.Dimension(60, 23));
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B4.setText("4");
        B4.setMaximumSize(new java.awt.Dimension(60, 23));
        B4.setMinimumSize(new java.awt.Dimension(60, 23));
        B4.setPreferredSize(new java.awt.Dimension(60, 23));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setText("5");
        B5.setMaximumSize(new java.awt.Dimension(60, 23));
        B5.setMinimumSize(new java.awt.Dimension(60, 23));
        B5.setPreferredSize(new java.awt.Dimension(60, 23));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setText("6");
        B6.setMaximumSize(new java.awt.Dimension(60, 23));
        B6.setMinimumSize(new java.awt.Dimension(60, 23));
        B6.setPreferredSize(new java.awt.Dimension(60, 23));
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B2.setText("2");
        B2.setMaximumSize(new java.awt.Dimension(60, 23));
        B2.setMinimumSize(new java.awt.Dimension(60, 23));
        B2.setPreferredSize(new java.awt.Dimension(60, 23));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B1.setText("1");
        B1.setMaximumSize(new java.awt.Dimension(60, 23));
        B1.setMinimumSize(new java.awt.Dimension(60, 23));
        B1.setPreferredSize(new java.awt.Dimension(60, 23));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B3.setText("3");
        B3.setMaximumSize(new java.awt.Dimension(60, 23));
        B3.setMinimumSize(new java.awt.Dimension(60, 23));
        B3.setPreferredSize(new java.awt.Dimension(60, 23));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        Bpoint.setText(".");
        Bpoint.setMaximumSize(new java.awt.Dimension(60, 23));
        Bpoint.setMinimumSize(new java.awt.Dimension(60, 23));
        Bpoint.setPreferredSize(new java.awt.Dimension(60, 23));
        Bpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpointActionPerformed(evt);
            }
        });

        B0.setText("0");
        B0.setMaximumSize(new java.awt.Dimension(60, 23));
        B0.setMinimumSize(new java.awt.Dimension(60, 23));
        B0.setPreferredSize(new java.awt.Dimension(60, 23));
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        Bneg.setText("(-)");
        Bneg.setMaximumSize(new java.awt.Dimension(60, 23));
        Bneg.setMinimumSize(new java.awt.Dimension(60, 23));
        Bneg.setPreferredSize(new java.awt.Dimension(60, 23));
        Bneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(B1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(B0, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bpoint, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bneg, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(B7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, Bneg, Bpoint});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bneg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, Bneg, Bpoint});

    }// </editor-fold>//GEN-END:initComponents



    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
       GUI.eq+="0";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B0ActionPerformed
    
    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        GUI.eq+="1";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        GUI.eq+="2";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        GUI.eq+="3";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        GUI.eq+="4";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        GUI.eq+="5";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        GUI.eq+="6";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B6ActionPerformed
    
    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        GUI.eq+="7";
         GUI.TextDisp.setText(GUI.hist+GUI.eq);
     }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        GUI.eq+="8";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        GUI.eq+="9";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_B9ActionPerformed

    private void BpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpointActionPerformed
        GUI.eq+=".";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BpointActionPerformed

    private void BnegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnegActionPerformed
       GUI.eq+="-";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BnegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton Bneg;
    private javax.swing.JButton Bpoint;
    // End of variables declaration//GEN-END:variables

}
