/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Trig.java
 *
 * Created on Feb 22, 2010, 4:57:51 PM
 */

package GUIMain;

/**
 *
 * @author Kal
 */
public class Trig extends javax.swing.JPanel {

    /** Creates new form Trig */
    public Trig() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bsin = new javax.swing.JButton();
        Bcos = new javax.swing.JButton();
        Btan = new javax.swing.JButton();

        Bsin.setText("SIN");
        Bsin.setMaximumSize(new java.awt.Dimension(60, 23));
        Bsin.setMinimumSize(new java.awt.Dimension(60, 23));
        Bsin.setPreferredSize(new java.awt.Dimension(60, 23));
        Bsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsinActionPerformed(evt);
            }
        });

        Bcos.setText("COS");
        Bcos.setMaximumSize(new java.awt.Dimension(60, 23));
        Bcos.setMinimumSize(new java.awt.Dimension(60, 23));
        Bcos.setPreferredSize(new java.awt.Dimension(60, 23));
        Bcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcosActionPerformed(evt);
            }
        });

        Btan.setText("TAN");
        Btan.setMaximumSize(new java.awt.Dimension(60, 23));
        Btan.setMinimumSize(new java.awt.Dimension(60, 23));
        Btan.setPreferredSize(new java.awt.Dimension(60, 23));
        Btan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bsin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bcos, Bsin, Btan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                .addComponent(Bsin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Bcos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Btan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bcos, Bsin, Btan});

    }// </editor-fold>//GEN-END:initComponents

    private void BsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsinActionPerformed
        GUI.eq+=" sin( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BsinActionPerformed

    private void BcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcosActionPerformed
    	GUI.eq+=" cos( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BcosActionPerformed

    private void BtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtanActionPerformed
    	GUI.eq+=" tan( ";
        GUI.TextDisp.setText(GUI.hist+GUI.eq);
    }//GEN-LAST:event_BtanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcos;
    private javax.swing.JButton Bsin;
    private javax.swing.JButton Btan;
    // End of variables declaration//GEN-END:variables

}
